### ISSUE TITLE
Split_FeatureScatter missing correlation output

### ISSUE THREAD

**Issue by skim245** [samuel-marsh/scCustomize#116]
Thank you for scCustomize !

"Split_FeatureScatter" is missing correlation output when I use two genes as feature1 and feature2. 
and split.by a group of interest. 
are there any options to display the output? 

Thank you in advance!

**Comment by samuel-marsh** [comment]
Did post-hoc calculation and plotting work for you?

I thought I'd also add one more example for why this can be tricky.

So above we showed that just within B cells correlation was 0.07.

Now we can also do this across all cells.  For reference in pbmc3k dataset there is only 1 non-B cell that expresses both of these genes and 137 cells total that express one or both.

However, the correlation is now 0.34.  The issue again being all the zeros.  In fact if we remove all the cells which express either gene and are not B cells then the correlation increases to 0.41 (because majority of cells are 0,0 for both genes.  But the correlation in actual expressing cells (what we really care about) hasn't changed.

Best,
Sam

**Comment by skim245** [comment]
@samuel-marsh thank you for clear rationales and post-hoc calculation suggestion! the plotting works great but as you mentioned the zeros largely affects the correlation output. I will be cautious interpreting the results. 
Thank you again!
