### ISSUE TITLE
Problem with reading multiple h5 files using Read10X_h5_Multi_Directory()

### ISSUE THREAD

**Issue by peculiar97** [samuel-marsh/scCustomize#124]
Hello,

I am trying to read & merge several matrix h5 files using Read10X_h5_Multi_Directory(). But it seems it is not able to find the files.
All these files (MantonBM5_HiSeq_1_raw_feature_bc_matrix.h5,
MantonBM6_HiSeq_1_raw_feature_bc_matrix.h5,
MantonBM3_HiSeq_1_raw_feature_bc_matrix.h5) are in **test** folder. 

```r
merged_h5 = Read10X_h5_Multi_Directory(base_path = "path/to/test" ,default_10X_path = F, h5_filename = "_HiSeq_1_raw_feature_bc_matrix.h5")
```
When running the following error pops up:

```r
Error in `Read10X_h5_Multi_Directory()`:
! Full Directory does not exist "test/NA/" was not found.
Run `rlang::last_trace()` to see where the error occurred.
```
  
Any help would be much appreciated!

**Comment by samuel-marsh** [comment]
Hi,

Just to clarify, are all of the files inside test folder?  Or are they in subfolders inside test folder?

Best,
Sam

**Comment by peculiar97** [comment]
> Hi,
> 
> Just to clarify, are all of the files inside test folder? Or are they in subfolders inside test folder?
> 
> Best, Sam

Thanks for the quick reply!

All the files are just in one folder (test). There are no subfolders.

**Comment by samuel-marsh** [comment]
Gotcha!

So the issue is just difference between two of the package functions.  What you used `Read10X_h5_Multi_Directory` is for when you have multiple subdirectories each containing one sample (i.e. outputs from Cell Ranger count or other tools).

What you want when all files are in one directory is `Read10X_h5_GEO`.  This function then uses the file prefix (i.e. when you get files from GEO, or manually rename, etc) and names files from single directory according to those prefixes.

So the code you want to run is:
```
merged_h5 <- Read10X_h5_GEO(base_path = "path/to/test" , shared_suffix = "_HiSeq_1_raw_feature_bc_matrix.h5")
```

If that doesn't work or you have other issues please let me know and I'll reopen the issue.

Best!
Sam

**Comment by peculiar97** [comment]
Dear Sam,
Thanks for the clarification!
Using Read10X_h5_GEO & removing "shared_suffix" argument solved the problem. 
```r
merged_h5 <- Read10X_h5_GEO(data_dir= "path/to/test/" )
```
Regarding `Read10X_h5_Multi_Directory`, I am curious if the "test" folder has three different subfolders(test1,test2,test3) and each subfolder has one specific h5 file(**MantonBM[1-3]**_HiSeq_1_raw_feature_bc_matrix.h5), what are the right argument values for  `Read10X_h5_Multi_Directory()` function?

**Comment by samuel-marsh** [comment]
Hi,

So you should still use shared_suffix but I had error in my code I sent (I'm currently fixing this in dev branch so it doesn't cause error):

```
merged_h5 <- Read10X_h5_GEO(base_path = "path/to/test" , shared_suffix = "_HiSeq_1_raw_feature_bc_matrix")
```

So, multi-directory function is made for instances (like the output of running Cell Ranger count on multiple samples) where each sample file has the same name but is located inside subfolder that is the sample name (see example here: https://samuel-marsh.github.io/scCustomize/articles/Read_and_Write_Functions.html#import-10x-genomics-tsv-mtx) this is showing the version when using `Read10X_Multi_Directory` but the principle is the same for the h5 version.

Currently the function doesn't support subdirectory reading if the files already haven't different names which distinguish the files from each other though.  So in order to work in requires files have same name.

Hope that is clear and let me know if you have any other questions!
Best,
Sam

**Comment by peculiar97** [comment]
> Hi,
> 
> So you should still use shared_suffix but I had error in my code I sent (I'm currently fixing this in dev branch so it doesn't cause error):
> 
> ```
> merged_h5 <- Read10X_h5_GEO(base_path = "path/to/test" , shared_suffix = "_HiSeq_1_raw_feature_bc_matrix")
> ```
> 
> So, multi-directory function is made for instances (like the output of running Cell Ranger count on multiple samples) where each sample file has the same name but is located inside subfolder that is the sample name (see example here: https://samuel-marsh.github.io/scCustomize/articles/Read_and_Write_Functions.html#import-10x-genomics-tsv-mtx) this is showing the version when using `Read10X_Multi_Directory` but the principle is the same for the h5 version.
> 
> Currently the function doesn't support subdirectory reading if the files already haven't different names which distinguish the files from each other though. So in order to work in requires files have same name.
> 
> Hope that is clear and let me know if you have any other questions! Best, Sam

Running 
```r
merged_h5 <- Read10X_h5_GEO(base_path = "path/to/test" , shared_suffix = "_HiSeq_1_raw_feature_bc_matrix.h5")
```
 gave me an error. So I just removed the "shared_suffix" argument. But good to know that you are addressing this in a later version. It would also be handy if "Read10X_Multi_Directory" could handle files with different names perhaps using regular expressions for the "shared_suffix" argument.
 
 Anyway, thanks for sharing such a convenient package in the single-cell world!

**Comment by samuel-marsh** [comment]
Hi,

Yes so the issue with the original code I posted is that previously the `shared_suffix` parameter would error if the file extension was included in what was provided to that parameter.  So if you provide just "_HiSeq_1_raw_feature_bc_matrix" it should work (and save you from having overly long file names).

You can always fix that by providing custom set of sample names to the `sample_names` parameter (must be in the same order as the files in directory) or simply renaming the entries in list with `gsub` after reading in the data.

However, that necessity that file extension by excluded wasn't really necessary and definitely tripped me up couple times too.  Develop branch now (v1.1.3.9023) now contains a fix so that function will work regardless of whether the file extension is part of `shared_suffix` or not.

I will work on potentially adding new functionality to the multi-directory functions down the line (probably within the next month).

Best,
Sam
