### ISSUE TITLE
offer figure_plot = TRUE for FeaturePlot_scCustom 

### ISSUE THREAD

**Issue by wwzhang** [samuel-marsh/scCustomize#127]
Could it possible to add an option to remove axes similar to  figure_plot = TRUE  of DimPlot_scCustom? figure_plot = TRUE is a quite a handy feature for 2d plots but sadly it is not available for FeaturePlot

**Comment by samuel-marsh** [comment]
Hi,

Thanks for submitting this issue!  This had been in my to do list for while but appears to have been lost along the way.  I have just added it to my V5 compatibility ToDo list.  I’ll update here when it’s implemented in develop branch.

Thanks,
Sam

**Comment by samuel-marsh** [comment]
Hi,

Just wanted to give you an update.  This is still on to do list but unfortunately is likely going to be bumped until after the v2.0.0 release coming up to match up with full Seurat 5 release.  Unfortunately, as one person team just not enough bandwidth to execute before Seurat5 release.  I'm actually going to work on making `Figure_Plot` its own function that can be supplied following plots like ggplot theming so that it can easily be called for any DimPlot based plot.  I'll update in next few weeks when I have it working in dev branch.

Best,
Sam

**Comment by wwzhang** [comment]
Thank you.

On a side note, will seuratv5 change a lot functions of sccustomize?

**Comment by samuel-marsh** [comment]
I’ve been working to ensure functions aren’t impacted but inevitably probably will be couple bugs in first release (there always are).  But as of right now with my testing all functions are working as expected (most of that credit though goes to Seurat devs for ensuring backwards compatibility of Seurat 5 with existing workflows).  Number of new functions and added capabilities/parameters also coming in v2.0.0 release.

Changes/Updates thus far can be found here;
https://github.com/samuel-marsh/scCustomize/blob/develop_V5/NEWS.md

Best,
Sam

**Comment by wwzhang** [comment]
thanks

**Comment by samuel-marsh** [comment]
Hi @wwzhang,

This enhancement has been implemented now in "develop_V5" branch v1.9.9.9040 in all 2D DR plots.  If you run into any issues with the `figure_plot` parameter after this update please let me know and I can reopen issue.

Best,
Sam
