### ISSUE TITLE
Featureplot color scale limits

### ISSUE THREAD

**Issue by Prathyusha-konda** [samuel-marsh/scCustomize#135]
Hi Samuel, thanks so much for this great package. I was wondering if there is a way to adjust the color scale on feature plot. For instance, if using Seurat's default, this is usually how I'd set limits: 

FeaturePlot(seurat_sub, features = "module", order = T) + 
  scale_color_gradientn(colors = plasma(n = 10, direction = -1), limits = c(0, 0.5))

Is there a way to do similar thing with scCustom? right now, when I do this, the na_color doesn't stay lightgrey anymore. Sorry if this is too naive. Thanks!

**Comment by samuel-marsh** [comment]
Hi @Prathyusha-konda,

Thanks for kind words!  Can you explain little more about rationale for changing the limits of the plot?  The reason it doesn’t work when you manually do it is because it’s overriding scCustomize’s post plot theming.  But I’m open to discussing modifying that.

Best,
Sam

**Comment by Prathyusha-konda** [comment]
> Hi @Prathyusha-konda,
> 
> Thanks for kind words! Can you explain little more about rationale for changing the limits of the plot? The reason it doesn’t work when you manually do it is because it’s overriding scCustomize’s post plot theming. But I’m open to discussing modifying that.
> 
> Best, Sam

Hi Samuel, 

I am trying to plot trajectories on top of feature plots (metadata) using ggpath and want all the plots to have a similar scale for comparison. I am currently doing this by plotting each metadata variable individually and then combining using wrap_plots since I can't seem to add ggpath to all plots when I assign all variables to features.

When I do this, the color for na_cutoff seems to change from lighter grey and darker grey and I can't seem to modify it :) I was wondering if there is a way to customize this further. It's not a highly important feature, but I was only curious :)

Thanks.
Prathyusha

**Comment by samuel-marsh** [comment]
Hi Prathyusha,

So I'd recommend against limiting the scale as you are doing because it causes problems in the visualization of the feature expression.  Here is example:

```
FeaturePlot(object = pbmc, "FOS", order = T) +
  scale_color_gradientn(colors = plasma(n = 10, direction = -1), limits = c(0, 0.5))

FeaturePlot_scCustom(pbmc, "FOS")
```

![image](https://github.com/samuel-marsh/scCustomize/assets/38284410/15d81d65-ca4a-442f-9fc7-a2b35cb0dcd5)
![image](https://github.com/samuel-marsh/scCustomize/assets/38284410/e6966ce7-b912-42a3-aed0-09a3e8b89e0f)


As you can see in the first example the majority of point actually get colored gray because they are above the scale.  So it can cause issues in the visualization.

I don't really recommend because putting everything on same scale causes issues in not well differentiating between high and low expressed features.  If needed you could always "normalize" expression by changing data to make highest expressing cell 1 and every other cell as percent of that.  You can do that for each feature and they would all be the same.  But it's just problematic visualization because telling the difference between high and low expression in these plots is important.

Best,
Sam

**Comment by Prathyusha-konda** [comment]
> Hi Prathyusha,
> 
> So I'd recommend against limiting the scale as you are doing because it causes problems in the visualization of the feature expression. Here is example:
> 
> ```
> FeaturePlot(object = pbmc, "FOS", order = T) +
>   scale_color_gradientn(colors = plasma(n = 10, direction = -1), limits = c(0, 0.5))
> 
> FeaturePlot_scCustom(pbmc, "FOS")
> ```
> 
> ![image](https://user-images.githubusercontent.com/38284410/277772060-15d81d65-ca4a-442f-9fc7-a2b35cb0dcd5.png) ![image](https://user-images.githubusercontent.com/38284410/277772108-e6966ce7-b912-42a3-aed0-09a3e8b89e0f.png)
> 
> As you can see in the first example the majority of point actually get colored gray because they are above the scale. So it can cause issues in the visualization.
> 
> I don't really recommend because putting everything on same scale causes issues in not well differentiating between high and low expressed features. If needed you could always "normalize" expression by changing data to make highest expressing cell 1 and every other cell as percent of that. You can do that for each feature and they would all be the same. But it's just problematic visualization because telling the difference between high and low expression in these plots is important.
> 
> Best, Sam

Thanks, Sam. My purpose for using the limits is not the same as you showed in the examples. I'm using them to compare metadata. A module with a score of 0.3 vs one with a score of 1 can't be considered the same and hence using same limits will help compare and contrast as to which module is higher. 

I was only curious to know if there's a way to adjust the na_cutoff color in this case, but it's fine without that as well.

Best, 
Prathyusha
