### ISSUE TITLE
Clustered_Doptplot by feature groups 

### ISSUE THREAD

**Issue by marshelma** [samuel-marsh/scCustomize#139]
Thank you for generating this amazing package. 

Would it be possible to allow passing a list of features to the Clustered_Dotplot and visualize by feature groups as implanted by the Seurat Dotplot in this request?

https://github.com/satijalab/seurat/issues/3174

**Comment by samuel-marsh** [comment]
Hi @marshelma,

Thanks for kind words and so glad package is helpful!!  I will look into this but it might be challenging due to `Clustered_DotPlot` being ComplexHeatmap based rather than ggplot2 but I’ll look into it.  

As note this will probably be not for week or so (or potentially early Dec) as I’m finishing up release of v2.0.0 (ideally to CRAN next week) and then have grant due Dec.  but I’ll keep you updated here as I look into it.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @marshelma,

I don't know whether this is truly going to be possible for me to implement with current bandwidth.  I would happily welcome a PR if this is something you are interested in but unfortunately don't think I'm going to be able to get to it myself.

Best,
Sam
