### ISSUE TITLE
Restrict titles only on the first row in featureplots when using split.by with more than one gene

### ISSUE THREAD

**Issue by ishwarvh** [samuel-marsh/scCustomize#146]
Hi Sam,

When using `split.by` argument in the `Featureplot_scCustom` function, each plot is labeled with its own title when plotting multiple genes. Would it be possible to just have one title per column like the native Seurat `FeaturePlot`

Here is what I see with `FeaturePlot_scCustom`:
![image](https://github.com/samuel-marsh/scCustomize/assets/4574151/b69ac6f7-50ff-4316-9438-af93e6981871)

Expected behaviour as seen with native Seurat `FeaturePlot` function:
![image](https://github.com/samuel-marsh/scCustomize/assets/4574151/71234f4b-6afb-4ff0-bb5d-48110d2541a6)

I checked if there is an option that can be passed to `Featureplot_scCustom` to see this behaviour, but couldnt find one. Please correct me if I am wrong.

Thank you,
Ishwar

**Comment by samuel-marsh** [comment]
Hi Ishwar,

So this was actually intentional design decision with `FeaturePlot_scCustom` that allows users to still set custom number of columns when using `split.by` which is not possible in Seurat natively.  However there is way that you can modify the plots yourself posthoc.

You simply need to edit the patchwork to remove the titles from undesired plots.  Here is example:


```
pbmc3k <- pbmc3k.SeuratData::pbmc3k.final

pbmc3k <- UpdateSeuratObject(pbmc3k)
pbmc3k <- subset(pbmc3k, idents = c('Naive CD4 T', 'CD14+ Mono')) 

plots <- FeaturePlot_scCustom(pbmc3k, c('MS4A1', 'CD74'), split.by = 'seurat_annotations')
plots

plots[[2]][[1]] <- plots[[2]][[1]] + theme(plot.title = element_blank())
plots[[2]][[2]] <- plots[[2]][[2]] + theme(plot.title = element_blank())

plots


```

![image](https://github.com/samuel-marsh/scCustomize/assets/38284410/701da437-4477-4c12-acae-2deae6639783)
![image](https://github.com/samuel-marsh/scCustomize/assets/38284410/a6d887ea-880a-4bd9-b95a-bb6c0f66e047)

**Comment by ishwarvh** [comment]
Thank you for explaining the rationale behind the design and the way to obtain the desired results.
