### ISSUE TITLE
Request option to change colour of NA values when plotting

### ISSUE THREAD

**Issue by SamuelCWJ** [samuel-marsh/scCustomize#147]
Hi! Thank you so much for this great package!

Please would it be possible to include the ability to change the colour of NA values when plotting, for example in DimPlot_scCustom? Sometimes the default grey colour isn't distinct enough from the other colours. Seurat has this option in its DimPlot (na.values =) function (https://satijalab.org/seurat/reference/dimplot), though it only works when using a custom scale colour palette. 

Thank you!

Best Regards,
Samuel

**Comment by samuel-marsh** [comment]
Hi Samuel,

Thanks for kind words!  Can you clarify instances where you would expect NA values when using `DimPlot`?  Just trying to figure out what is needed where so I can test the issue/potential fix.

Thanks!
Sam

**Comment by SamuelCWJ** [comment]
> Hi Samuel,
> 
> Thanks for kind words! Can you clarify instances where you would expect NA values when using `DimPlot`? Just trying to figure out what is needed where so I can test the issue/potential fix.
> 
> Thanks! Sam

Hello and thank you for your reply!

Here's one example I can think of: 
I have categorised my samples by what disease group or condition they come from (in the metadata). However, not all of the samples have proper information, hence their values would be NA under the disease column in the metadata. This would apply to all other kinds of labelling in the metadata columns too. When I plot a UMAP for example using DimPlot, I would use these labels to visualise my categories using the "group.by" argument. It would be nice to distinguish these NA values a bit more distinctly from the other labels!

Thank you!

Samuel

**Comment by samuel-marsh** [comment]
Hi @SamuelCWJ,

Very sorry for delay in getting back to you!  So in that case I would suggest instead of setting values as NA (which R treats differently) I would set unknown or not-provided values to something like "Unknown", "Unk", or "NS".  That way they aren't treated as NA by R functions.  By setting the meta.data column to a factor and setting those categories as final element in factor you can better control their color simply as part of providing color vector to plot (and they'll appear at the bottom of any plot legend).

Hope this helps!
Best,
Sam
