### ISSUE TITLE
Add option to control stroke size for plotting smaller dots

### ISSUE THREAD

**Issue by nikofleischer** [samuel-marsh/scCustomize#148]
Hi,
thanks a lot for the great and continued updates. 

I have a small feature request, that has already been posted in the original Seurat Repo [Seurat Repo](https://github.com/satijalab/seurat/issues/7087#issue-1647408853), but as it is known for years, I sense hesitancy to implement. As stated there, it is an issue inherent to ggplot 2.0 as discussed on [SO](https://stackoverflow.com/questions/34638902/point-size-in-ggplot-2-0-0) that changes the default stroke of geom point, so the minimum dot size is much larger. 

It would be great expose a simple parameter to all the plotting functions to manipulate stroke size for geom_plot calls. When plotting large number of points, even with pt.size = 0.1 plots get overplotted very quickly and with imbalanced group sizes shuffle = TRUE doesn't help much. There is a workaround hack by temporarily editing SingleDimPlot, but having it safely in scCustomize would just be great! 

Thanks a lot, 
Niko

**Comment by samuel-marsh** [comment]
Hi Niko,

So my guess is that rather than hesitancy it is matter of prioritization and time to test/implement fix vs. need for the fix (again totally my guess as I'm not member of dev team).  It would be hard to implement directly in scCustomize without also adding customized version of `SingleDimPlot` which I'm hesitant to do because it makes things much more fragile in terms of keeping scCustomize current with internals of Seurat plotting functions.

However, the fix does seem to be simple so I'm going to look into submitting PR to Seurat directly to add this parameter.  Can't guarantee devs will implement it but it is more likely if they just have to run checks vs. implement themselves when focus may be elsewhere.  I can post back here with update.

Alterantively, if you have way to implement the fix within the current framework of scCustomize that doesn't rely on implementing `SingleDimPlot` in scCustomize I would be happy to test myself or if you want to submit PR I can take a look.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi Niko,

Submitted PR to Seurat to potentially add the parameter. 

Best,
Sam

**Comment by samuel-marsh** [comment]
Closing this for now and hope to see Seurat accept the PR.  

Best,
Sam
