### ISSUE TITLE
Feature Co-Expression

### ISSUE THREAD

**Issue by pwmellors** [samuel-marsh/scCustomize#156]
Hi Sam,

Thanks for this wonderful package.  I have found your feature plots in particular to be immensely helpful and a significant upgrade.  

I was curious if you knew of a way to illustrate co-expression of two features with scCustomize.  I find the function in Seurat that allows this to be unhelpful, example below.  Perhaps I am reading the corresponding color legend incorrectly, but it seems this only does a good job of illustrating co-expression when both genes are each very highly expressed in a given cell (= yellow), and anything less than this very difficult to discern (different shades of green, red, grey.  I also dislike, as in the Seurat feature plot function in general, that there is no distinction between 0 and expression and low expression (both = grey), which is why I use scCustomize for FP in general. Thanks!

[CD103_CD49a.pdf](https://github.com/samuel-marsh/scCustomize/files/14213888/CD103_CD49a.pdf)

**Comment by samuel-marsh** [comment]
Hi @pwmellors,

Thanks for the kind words!

Unfortunately, my feelings are pretty much the same as yours which is why I haven't done anything to update blend plots.  I don't think there any good color schemes which one can actually interpret (even when expression levels of both genes are hard it is very tricky).  I tried playing around with changing color schemes and it still was bad in my opinion.

In terms of what you can do I think there are couple things that start to get at it.  First, you can use the joint density plots (`Plot_Density_Joint_Only`) to look at coexpression to a degree.  Heatmaps can also start to get at this.

If you really want to get at numbers the best I can suggest is actually just a tabular data solution.  Use `FetchData` to pull the genes of interest (along with any clustering or grouping variables you need).  Then create filtered data.frame filtering on expression in both (or more than 2 genes).  And then use filtered and original to calculate percents.  However, I would caution here that data sparsity can create issues and may make these percents appears artificially lower than they are (especially if filtering on more than 2 genes).  So I would kind of say this kind of approach is lowest on my list.

If you have any thoughts on visual idea now or in future please feel free to comment here and I'm happy to give it a look!

Thanks again!
Sam
