### ISSUE TITLE
as.anndata issue

### ISSUE THREAD

**Issue by williamsdrake** [samuel-marsh/scCustomize#162]
Hi,

Great package - use it all the time. I saw you recently added as.anndata as a function. It works great - however I initially had an issue. Here is the code/error: 

```
> as.anndata(x = combined_s, file_path = "/data/Anndata/", file_name = "combined.h5ad")
• Checking Seurat object validity & Extracting Data
• Creating anndata object.
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'anndata'
Run `reticulate::py_last_error()` for details.
In addition: Warning messages:
1: Adding a command log without an assay associated with it 
2: Adding a command log without an assay associated with it 
3: Adding a command log without an assay associated with it 

```

I previously had a python environment which did not require anndata. It was easy enough to install it using
```
> library(reticulate)
> py_install("anndata")
```
which fixed the issue. It would be nice if there was a check to see if the python environment contains anndata already and if not either install it or return a message asking the user to install it.

**Comment by samuel-marsh** [comment]
Hi @williamsdrake,

Thanks for kind words and feedback!  I agree it is probably better to have a more informative error message after a check for anndata.  I will add that to my list for next version update.

I hesitate to add direct installation because I don’t want to directly modulate users python and reticulate environments as cross talk can be tricky for some.  

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi @williamsdrake,

This is now updated and present in develop branch (v2.1.2.9018 or greater).  Thanks again for reporting issue!

Best,
Sam
