### ISSUE TITLE
Enable `Add_Cell_QC_Metrics()` to Support ENSEMBL IDs for "IEG" and "MSig_DB"

### ISSUE THREAD

**Issue by JuanTejedor** [samuel-marsh/scCustomize#186]
Hi Sam,

Thank you for your excellent work on the package; it has been incredibly useful!

I encountered an issue with the `Add_Cell_QC_Metrics()` function when using ENSEMBL IDs in a `SeuratObject`. Currently, the function does not support adding "IEG" and "MSig_DB" genes because the associated data frames are formatted with GENE IDs only. As a result, `Add_Cell_QC_Metrics()` fails to identify these genes when ENSEMBL IDs are used.

Since there is already an `ensembl_ids` argument in `Add_Cell_QC_Metrics()`, maybe it could be enhanced to support both ENSEMBL and GENE IDs by updating the "IEG" and "MSig_DB" data frames to include ENSEMBL IDs as well.

Additionally, a feature to rename features within the `SeuratObject`, such as converting between ENSEMBL IDs and GENE IDs, would be highly beneficial.

Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi @JuanTejedor,

Thanks for kind words!  Yes I can work on updating those lists to include ensembl IDs as well.

In terms of renaming features I have intentionally decided to avoid such a direct function because I get worried about the potential ways it could break with future updates to Seurat and/or inappropriate use.

The way that I handle this when I need to convert is to create data.frame with Ensembl_IDs and matched feature names (If changing from ensembl to names make sure that ensembl ID order in the data.frame exactly matches order in object; or vice versa for names to ensembl).  Then extract matrix, rename the rows, create Assay (or Assay5 object) and then replace current assay.
Take care though as this will also replace any Assay meta.data or variable features for that assay.
```
pbmc_mat <- LayerData(pbmc, layer = "counts")

rownames(pbmc_mat) <- names_df$feature_names

new_assay <- CreateAssay5Object(counts = pbmc_mat, data = NULL, min.cells = 0, min.features = 0)

pbmc[["RNA"]] <- new_assay
```

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @JuanTejedor,

Ok update is live in the release branch (release/2.2.0; v2.1.2.9066+).  Works for both Seurat and Liger versions of the functions.  If you have any issues using new features please let me know and I'll reopen the issue.

Best,
Sam
