### ISSUE TITLE
Setting a scale/limit for `scCustomize::Plot_Density_Custom`?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [samuel-marsh/scCustomize#192]
Hi there, 

Thanks for the tool. The `scCustomize::Plot_Density_Custom` provides a very nice visualisation of UMAP for features, but it could be misleading depending on the range of values of a given feature, especially if having multiple plots. 

I wonder if it would be possible to set/adjust the limit of the density from 0-1 for the plot?

Thank you for your work!

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub,

Can you explain what you mean by plots being misleading?

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
I was hoping to include multiple density UMAP plots for different numerical QC features, e.g., percent.mt, cell cycle gene score, etc. 

At the moment, each plot has its own legend of density according to the range of values for a given feature. This is fine, but I think it could be visually misleading when there are multiple density plots in 1 figure. For example when looking at percent.mt below. One might (without careful examination of the legend) determine that that cluster of cells should be removed because it has too high of mitochondrial content. But, actually that is only relative to the other cells, and the density max value for this plot is in fact very low (~0.04). 

Perhaps, density plot is not the best in this case, but just some thoughts. What do you think? 

Thanks, Sam.

<img width="742" alt="Screenshot 2024-08-04 at 12 47 55" src="https://github.com/user-attachments/assets/47cffcdb-a30d-4635-956d-60bd10adfe78">

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub,

So unfortunately this is not something I want to implement and also don’t think should be done given what the plots and data represent.  Moving to 0-1 scale would not be appropriate for these plots because it would remove the density scale which you don’t want to do.

Additionally, things like percent mito are poor to represent with density plot especially if showing a QC metric and potential choice of cutoff.  Precisely because they are not intelligible.

Even with features, one has to be very careful in the interpretation of density in UMAP space.  It can be very problematic and I often don’t use when plotting a single feature because it doesn’t yield anything that a simple feature plot doesn’t and causes issues when comparing two genes to each other and might actually be a misleading visualization due to meaning of density in UMAP space.

Where I think density plots can be useful is plotting joint density of two or more features.  In practice this is much more intelligible than blended FeaturePlot to show that a group of features is jointly expressed in group of cells.

How that makes sense.

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
Hi, Sam - Thanks for the response. That makes sense. 

Unrelated to the scaling, is it quick to add an argument for plotting a categorical metadata variable as label in `scCustomize::Plot_Density_Custom`?

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub,

So unfortunately that’s also something I don’t think I’ll be implementing at least in scCustomize.  Reason is two fold, first the density plots currently are customizations of Nebulosa package plots and I don’t have bandwidth to write branching plot code depending on variable type.

The second, and more important reason, goes back to discussion of what density means in UMAP space (which not a whole lot actually) and especially when it comes to a categorical variable.  Applying density kernel to these types of variables can cause significant problems in interpretation and analysis when dependent on UMAP plot.

I think the better visualizations to convey differential abundance differences are either plotting statistical results of DA testing (depending on method) or DA specific plots from DA packages (cna, Milo, etc).

Hope that makes sense.

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
I see. That is understandable. I was just referring to the ability to label the cluster's names on the plot (not using density plot to plot the categorical variable)
