### ISSUE TITLE
Updated_HGNC_Symbols using mouse genes

### ISSUE THREAD

**Issue by siv2108** [samuel-marsh/scCustomize#202]
Thank you for the great package! 

It would be great if the function to update gene symbols had added functionality for mouse genes, as right now it gives an error that there is a capitalization issue with the mouse genes. I basically tried running this, `results <- Updated_HGNC_Symbols(input_data = mm10_specific_genes)`, and got the following error: 

Error in `Updated_HGNC_Symbols()`:
! Uncovered potential errors in case/capitalization of input symbols.  Please check case is correct.
Backtrace:
 1. scCustomize::Updated_HGNC_Symbols(input_data = mm10_specific_genes). 

 Thanks for the advice on this issue!

**Comment by samuel-marsh** [comment]
Hi @siv2108,

Thanks for kind words!  As of right now I’m not sure I have bandwidth to create equivalent mouse function right now but I can look into it next week and update when I know for sure.  I wouldn’t use current function with mouse genes because of differences between human and mouse annotation and gene homology.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @siv2108,

I have just updated the release branch to include new function `Updated_MGI_Symbols` for use with mouse genes.  You can install release branch with:
```
devtools::install_github("samuel-marsh/scCustomize", ref = "release/2.2.0")
```

If you run into any issues with the function please let me know but seems to work in my testing.

Best,
Sam
