### ISSUE TITLE
Bug fixes (Plot_Density_Custom and Plot_Density_Joint_Only drawing) ；Picture saving

### ISSUE THREAD

**Issue by Roner2022** [samuel-marsh/scCustomize#212]
1. When you use ggsave to save the picture in the picture below, only the first one is kept by default, which is not very friendly to noobs, is there an alternative way to save two PDFs at a time?
![image](https://github.com/user-attachments/assets/bfa90cf7-22a2-4ac8-a40c-dbbe6464ffdb)
![image](https://github.com/user-attachments/assets/2267b536-e242-4f45-9dfc-e632dd178463)

2. Plot_Density_Custom and Plot_Density_Joint_Only functions can't be used? Can you fix it? 

![image](https://github.com/user-attachments/assets/ae6f8d51-ab9e-4171-87cc-9ac72a2e70a1)
R-4.4.1
ggplot2-3.5.1
Thank you

**Comment by samuel-marsh** [comment]
Hi @Roner2022,

The first issue you are having is because the dotplot created by `Clustered_DotPlot` is not a ggplot object while the km elbow plot is (dotplot is ComplexHeatmap based, which is stated in manual entry).  In order to save the dotplot you can just use the standard `pdf()` graphics device for saving.  If you want to save both plots to same pdf you can leave all settings as default.  If you want to only save the dotplot then just set `plot_km_elbow = FALSE` to only return the dotplot.

For the second issue please this has been solved in the dev branch (hope to push to CRAN soon).  But for now you can install with:
```
devtools::install_github("samuel-marsh/scCustomize", ref = "release/3.0.0")
```

Best,
Sam
