### ISSUE TITLE
common range between Density plot

### ISSUE THREAD

**Issue by TiphaineCMartin** [samuel-marsh/scCustomize#218]
I perform Plot_Density_Custom but I would like to split.by (one feature) as I am doing with FeaturePlot_scCustom and have the posibilities to define the range that I want to visualize the density

FeaturePlot_scCustom(gcdata,
                      features = "Mox1", label = TRUE, repel = TRUE,
                      split.by="genotype")

 Currently I use sub_set to split my data into 3 group that I have, but when I run Plot_Density_Custom. I don't have the same range and I did not find a way to improve the range of density .
p4 <- Plot_Density_Custom(seurat_object = gcdata, 
                           features = "Mox1")
 Idents(gcdata) <- "genotype"
 gcdata_WT <- subset(gcdata, idents = "WT", invert = FALSE)
 p1 <- Plot_Density_Custom(seurat_object = gcdata_WT, 
                           features = "Mox1")
 gcdata_g2 <- subset(gcdata, idents = "gentoype2", invert = FALSE)
 p2 <- Plot_Density_Custom(seurat_object = gcdata_g2, 
                           features = "Mox1")
 gcdata_g3<- subset(gcdata, idents = "gentoype3", invert = FALSE)
 p3 <- Plot_Density_Custom(seurat_object = gcdata_g3, 
                           features = "Mox1")
 wrap_plots(p1, p2, p3, p4, ncol = 2) + plot_annotation(tag_levels = 'A')
 

How I can do that ?

**Comment by samuel-marsh** [comment]
Hi @TiphaineCMartin,

So unfortunately this isn't really possible (or advised) with the density plotting functions due to the way that density calc works.  I typically use the joint density function mainly when using these functions because it can provide good representation of which clusters have good co-expression of series of markers.

If you are looking to show differences in expression/percent of expressing cells across groups then in my opinion things like violin and dotplot do and overall better job there (though have to be careful with dotplot when split with scaled data issues).

Best,
Sam

**Comment by TiphaineCMartin** [comment]
Thanks for your insight about this visualisation.
Tiphaine
