### ISSUE TITLE
Same scale bar for multiple features

### ISSUE THREAD

**Issue by jmrussell** [samuel-marsh/scCustomize#65]
I'm wondering if there is a way to set the scale to be the same for a list of features regardless of their expression, e.g. I set it to the highest value in a list of genes and they all share the same scale bar

**Comment by samuel-marsh** [comment]
Hi,

So not in scCustomize at the time being.  Although you can do this in Seurat:
```
FeaturePlot(pbmc, c("FOS", "CD3E"), keep.scale = "all")
```

The reason why I don't include this in scCustomize is because I think it confuses visualization.  If you have lowly expressed gene and highly expressed plotted on same scale then potential delta between cells in the lowly expressed gene is going to be wiped out by being forced to use small part of the available color scale and make differentiating between different values harder.

The other way people sometimes also do this is by plotting "normalized" expression (within each gene individually) with say arbitrary max value of 10.  So this avoids the first probably mentioned above where you condense the available color scale but creates the probably of not being able to compare between plots because everything is scaled identically so high expressors and low expressors can look exactly the same.

Hope that makes sense.
Best,
Sam
