### ISSUE TITLE
Flip clustered dotplot

### ISSUE THREAD

**Issue by france-hub** [samuel-marsh/scCustomize#69]
Hello Samuel,
Thanks for this package!
Is there a way to quickly flip a clustered_DotPlot?

Thanks!
Francesco

**Comment by samuel-marsh** [comment]
Hi Francesco,

Thanks for kind words!  I’m not sure of how to implement in complexHeatmap.  Let me look into it and get back to you.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi Francesco,

So currently the answer is no, not once plot is created.  However, I’m going to work on adding parameter to the function to transpose matrix before plotting which will result in flipped plot.  Appreciate your patience as I don’t currently have timeline for fix but will update here when addressed.

Thanks!
Sam

**Comment by france-hub** [comment]
Ok!Thans Samuel!

**Comment by samuel-marsh** [comment]
Reopening so I can keep track of issue.

**Comment by samuel-marsh** [comment]
Hi,

Sorry for delay here it's been busy time.  The fix for this issue is now live in the dev branch (v1.0.2.9036).  The new parameter is called `flip` and it takes logical input.  So setting `flip = TRUE` will flip it so that rows are idents and features are columns.

I am submitting the package to CRAN soon and this change will also be in new release once that is complete.

If you have any issues with this please let me know and I'll reopen the issue.

Best,
Sam
