### ISSUE TITLE
90 degree x label

### ISSUE THREAD

**Issue by AltayYuzeir** [samuel-marsh/scCustomize#84]
Hello. First thank you for creating this awesome package, it is a lifesaver!

I wanted to ask if it is possible to make the x label fully vertical, equivalent to "angle = 90" of element_text() in ggplot2. I am asking in regard to the stacked violin plot, which is awesome by the way. The x_lab_rotate = TRUE, provides 45 degrees rotation, as far as I understand. Using "+ theme()" from to set the angle did not work and using "& theme ()" from Patchwork introduced x axis lables to all stacked plots.

Thanks a lot.

**Comment by samuel-marsh** [comment]
Hi,

Thanks so much for kind words!!

Yes I think that shouldn’t be issue.  I’ll work on modified parameter today.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @AltayYuzeir,

The fix is now live in develop branch v1.1.0.9007.  The parameter x_lab_rotate will still work as before with FALSE being no rotation and TRUE being 45 degree rotation.  However, it now also accepts either a value of 45 (same as setting TRUE) or 90 for fully vertical labels.  It only accepts those values because hjust and vjust need to be set each time depending on angle so not practical right now to allow other values (plus I think between horizontal, vertical, and 45 degree that covers nearly all use cases).

Thanks for the suggestion!

Best,
Sam

**Comment by AltayYuzeir** [comment]
Hey, first thank you for the very rapid response. It works now, thank you so much!
